name: Delivery to Server

on:
  push:
    branches: [ master ]

jobs:
  delivering:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    - name: Pull Recent File
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.HOST }} "cd smk/;git reset --hard;git pull origin master;git checkout master;"
   
